// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCZQlpHRhNzYuhcMC7JrJZESW1sCE9cfc',
    appId: '1:883550739920:web:9c12c8f19f2a6594bdedd5',
    messagingSenderId: '883550739920',
    projectId: 'sizemet',
    authDomain: 'sizemet.firebaseapp.com',
    storageBucket: 'sizemet.firebasestorage.app',
    measurementId: 'G-QVEPD6YN2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYoTf3l1Coy8jwByRfk9lJkQLo_FfsRGQ',
    appId: '1:883550739920:android:801fa2719ae2c7e4bdedd5',
    messagingSenderId: '883550739920',
    projectId: 'sizemet',
    storageBucket: 'sizemet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGzLSso879xAMOEjj03TieuXtA55tS1p0',
    appId: '1:883550739920:ios:f2e9d0d3a9d55384bdedd5',
    messagingSenderId: '883550739920',
    projectId: 'sizemet',
    storageBucket: 'sizemet.firebasestorage.app',
    iosBundleId: 'com.sizemet.app.sizemet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGzLSso879xAMOEjj03TieuXtA55tS1p0',
    appId: '1:883550739920:ios:f2e9d0d3a9d55384bdedd5',
    messagingSenderId: '883550739920',
    projectId: 'sizemet',
    storageBucket: 'sizemet.firebasestorage.app',
    iosBundleId: 'com.sizemet.app.sizemet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCZQlpHRhNzYuhcMC7JrJZESW1sCE9cfc',
    appId: '1:883550739920:web:10d72ddcc2de5425bdedd5',
    messagingSenderId: '883550739920',
    projectId: 'sizemet',
    authDomain: 'sizemet.firebaseapp.com',
    storageBucket: 'sizemet.firebasestorage.app',
    measurementId: 'G-9RNZR4EK1R',
  );
}
